### ISSUE TITLE
Error with identity_map

### ISSUE THREAD

**Issue by plindner2** [elimereu/matchSCore2#10]
Hello,

I was wondering if you could help me troubleshoot this error message. I have gone through the user guide/vignette for matchSCore, including training the model and would now like to utilize the trained model and the `gene_cl.ref` that was used in the training of the model to identify cell subsets in my pre-processed and scaled Seurat object ("split.ccr.singlet.mouse"). Here is the code that I have been using:

```
BiocManager::install("scater")
library(scater)
library(Seurat)

"https://www.dropbox.com/s/lrfoux7uxundcy1/sce.all_classified.technologies.RData?raw=true"
load(file = "../Downloads/sce.all_classified.technologies.RData") 

"https://www.dropbox.com/s/wijdjhbm17fd7fp/markers_all_datasets.RData?raw=true"
load(file = "../Downloads/markers_all_datasets.RData")
ref.markers <- markers$Chromium
gene_cl.ref <- cut_markers(levels(ref.markers$cluster), markers = ref.markers, ntop = 100)

library(matchSCore2)
library(nnet)
library(Matrix)

mod <- train_model(scale.data = scaled, clus = nnet2,gene_cl.ref = gene_cl.ref, prop = 0.5)

mousescaled <- split.ccr.singlet.mouse@assays$RNA@scale.data

out <- identity_map(scale.data = mousescaled, model = mod, gene_cl.ref = gene_cl.ref)
```

And here is the error message that I have been getting:

```
Error in apply(var.test, 1, function(x) (x - min(x))/(max(x) - min(x))) : 
  dim(X) must have a positive length
```

**Comment by elimereu** [comment]
Hi, 

I know why you get this error. 
Seurat keep in the scale.data only the highly variable genes. 
Therefore, the markers in gene_cl.ref could not be there. 

To solve this, you can run before these commands:

mousescaled <- ScaleData(split.ccr.singlet.mouse, features= unlist(gene_cl.ref))
mousescaled <- split.ccr.singlet.mouse@assays$RNA@scale.data <mailto:assays$RNA@scale.data>

And then the command 

> out <- identity_map(scale.data = mousescaled, model = mod, gene_cl.ref = gene_cl.ref)`
> 

In this way, genes in the scale.data will contains at least a subset of those in the gene_cl.ref.
Pay attention to gene names, they need to be written with the same nomenclature.

I hope this help!

Thanks for asking this! 

Cheers, 

Elisabetta

**Comment by plindner2** [comment]
Hi Elisabetta,

Thanks for the speedy response. When I try to input the recommended line:

`mousescaled <- ScaleData(split.ccr.singlet.mouse, features= unlist(gene_cl.ref))`

I get the following error:

```
> mousescaled <- ScaleData(split.ccr.singlet.mouse, features= unlist(gene_cl.ref))
Centering and scaling data matrix
Error in txtProgressBar(min = 0, max = max.block, style = 3, file = stderr()) : 
  must have 'max' > 'min'
```

Any insight? Thanks for the continued help!

PL

**Comment by elimereu** [comment]
Hi, 

Could you show me the following outputs: 

1. head(split.ccr.singlet.mouse[,1:4])

2. str(gene_cl.ref)

I never seen this error..

**Comment by plindner2** [comment]
Hi Elisabetta,

The outputs for those codes are as follows:
```
> head(split.ccr.singlet.mouse[,1:4])
An object of class Seurat 
2 features across 4 samples within 2 assays 
Active assay: integrated (1 features)
 1 other assay present: RNA
 2 dimensional reductions calculated: pca, umap
> str(gene_cl.ref)
List of 8
 $ B cells          : chr [1:100] "CD79A" "FCRL1" "MS4A1" "ADAM28" ...
 $ CD14+ Monocytes  : chr [1:100] "FCN1" "S100A12" "S100A8" "S100A9" ...
 $ CD4 T cells      : chr [1:100] "IL7R" "CAMK4" "RPS12" "RPS6" ...
 $ CD8 T cells      : chr [1:100] "CCL5" "TRGC2" "GZMA" "GZMH" ...
 $ Dendritic cells  : chr [1:100] "FCER1A" "CLEC10A" "UPK3A" "HLA-DQB2" ...
 $ FCGR3A+ Monocytes: chr [1:100] "LYPD2" "CDKN1C" "C1QA" "FCGR3A" ...
 $ HEK cells        : chr [1:100] "CTTN" "RP5-1024N4.2" "CDKN2A" "TCEAL9" ...
 $ NK cells         : chr [1:100] "KLRF1" "PRF1" "GZMB" "KLRB1" ...
```

**Comment by elimereu** [comment]
I’m sorry, but I was wrong, what I want to see is the head of the first 4 columns of the scale.data matrix you are using.
Here the idea was to check if the names in the matrix and in gene_cl.ref are corresponding. Usually mouse has names like: “Cd79” while human “CD79” (all capital letters).

As I’m seeing you have the integrated dataset as active assay, I suggest you to use the RNA assays instead. 

Also I see that gene_cl.ref you are using is the human PBMC, so it’s weird you are using it in mouse cells. Am I wrong?

**Comment by plindner2** [comment]
Hi Elisabetta,

You are correct, the mouse genes are written with only the first letter capital and the rest lowercase. The idea is to use the human PBMC gene_cl.ref to get an idea about which clusters in the mouse dataset might be the different cell identities. 

I suppose an alternative plan would be to create a new gene_cl.ref using a different dataset with mice genes, but how would one go about doing that? Format, file type, etc?

PL

**Comment by elimereu** [comment]
What’s the tissue of origin from which your sample come from?
You should use a reference dataset that is similar to the tissue you are analyzing.

I think it doesn’t make any sense to use the PBMC gene_cl.ref in your case unless you are analyzing PBMC or similar
Immune cell types.

**Comment by plindner2** [comment]
Hi Elisabetta,

Ideally, we would love to use that, but I'm afraid it doesn't exist as we are using pregnant mouse decidua. From our scRNAseq data, we can easily identify the known remarkable cell types that are there. However, we are looking to use a more generic method for identifying the other clusters that are potentially DCs, Monocytes, and possibly cNKs - which is why the Human PBMC dataset would work just fine.

PL

**Comment by elimereu** [comment]
Ok, let’s suppose the gene_cl.ref is fine, you need to match gene names as they are in your scaled.matrix. 
So, you have to transform the gene_cl.ref names. Only the first letter have to be capital if this happens also in your matrix.

You can use the following commands:

simpleCap <- function(x) {
  x=tolower(x)
  s <- strsplit(x, " ")[[1]]
  paste(toupper(substring(s, 1,1)), substring(s, 2),sep="")
}

gene_cl.ref  <- lapply(gene_cl.chromium,function(x) sapply(x,simpleCap))

Please, consider to use the RNA assays when you compute the ScaleData. It will work better. 

Best, 

Elisabetta

**Comment by plindner2** [comment]
Hi Elisabetta. Thanks for this. I am getting a new error message. Sorry about all of the trouble, but thanks for helping. 

Code (updated):
```
#Train 
ref <- data.list$Chromium
nnet2 <- ref$nnet2
ref.markers <- markers$Chromium
scaled <- ref@assays$RNA@scale.data
gene_cl.ref <- cut_markers(levels(ref.markers$cluster), markers = ref.markers, ntop = 100)

### Training of the model  
mod <- train_model(scale.data = scaled, clus = nnet2,gene_cl.ref = gene_cl.ref, prop = 0.5)


#New Dataset
simpleCap <- function(x) {
  x=tolower(x)
  s <- strsplit(x, " ")[[1]]
  paste(toupper(substring(s, 1,1)), substring(s, 2),sep="")
}

lcgene_cl.ref  <- lapply(gene_cl.chromium,function(x) sapply(x,simpleCap))


## Testing on another dataset
mousescaled <- ScaleData(split.ccr.singlet.mouse, assay = 'RNA', features= unlist(lcgene_cl.ref))
mousescaled <- split.ccr.singlet.mouse@assays$RNA@scale.data

out <- identity_map(scale.data = mousescaled, model = mod, gene_cl.ref = lcgene_cl.ref)
identity_heatmap(out)
```

Output:

```
> out <- identity_map(scale.data = mousescaled, model = mod, gene_cl.ref = lcgene_cl.ref)
Error in apply(var.test, 1, function(x) (x - min(x))/(max(x) - min(x))) : 
  dim(X) must have a positive length
```

Thanks in advance,
PL

**Comment by elimereu** [comment]
Ok, I think everything should be more or less ok until the end.
Could you please check the output of table(out$ids) and summary(out$probabilities) ?

**Comment by elimereu** [comment]
Or maybe you don’t get that output.. not clear..

It looks that it doesn’t find at least one gene from mousescaled. 
Could you show me the head(mousescaled[,1:4])?

**Comment by plindner2** [comment]
Right, it looks like the issue is with the `identity_map` command so there is no `out` value. 

Here is the output, nevertheless:
```
> table(out$ids)
Error in eval(quote(list(...)), env) : object 'out' not found
> summary(out$probabilities) 
Error in summary(out$probabilities) : object 'out' not found
> head(mousescaled[,1:4])
Error in mousescaled[, 1:4] : subscript out of bounds
```

**Comment by elimereu** [comment]
The problem is that your mousescaled matrix is empty.

**Comment by plindner2** [comment]
Elisabetta,

I seem to have figured out the problem and now have the heatmap with cell identities. However, how do I convert that to the matchSCore2 clustering annotations?

On the code in the user guide:

```
smseq.clus <- smartseq2$ident
col=c("aquamarine","orange","green4","blueviolet","black","maroon","coral2","deepskyblue3","lightgray")
summary_barplot(class.fac = out$ids ,obs.fac = smseq.clus)+scale_fill_manual(values = col)
```

Should the "smseq.clus <- smartseq2$ident" come from my data or the original dataset if I am using the PBMC data?

Is that even the right code to accomplish this?

Best,
PL

**Comment by elimereu** [comment]
Hi,

Great! The cell type annotations are in the slot ids from out$ids.

**Comment by plindner2** [comment]
Elisabetta,

Super, but is there a code that plots them on the pre-clustered map like shown in the README.md file?
![image](https://user-images.githubusercontent.com/26147636/78831128-bec3e100-79ae-11ea-87d2-f4b64567e656.png)

**Comment by elimereu** [comment]
No, you have to compute the clustering with Seurat (for example) and then add in the meta.data the ids you get from the matchSCore2, so that you can color code them in the UMAP plot.
